# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13fc08043c8bf3c80bdd51792e34917d772ea5ccd803c6628669ea000d5817c0dc08e855a45d60305fac063991c71edcd0dee953985b544cb3dcc9ce776158c7

test:
  secret_key_base: 9336e8f535268bbac8d9851e860ea04cbf5da453b8e685a57360ef139fa63b1868e3ce422dc0e510468f7ae0c763b2397a038d00d16cbf1d03d7a6057b4ab114

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
